server:
  port: 8081

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://192.168.237.128:7001/eureka
  instance:
    instance-id: zuul-service
    prefer-ip-address: true

zuul:
  routes:
    order-service:
      path: /order/**
      service-id: order-service
  ribbon:
    eager-load:
      enabled: true    #启动完成后就进行加载
